/**
 * Bayra Memory System — Snapshot Module
 * Inspired by ZeroClaw's snapshot.rs
 * 
 * Atomic Soul Export: dumps important memories to MEMORY_SNAPSHOT.md
 * Auto-Hydration: if bayra.db is missing but snapshot exists, restores from it
 */

import { readFileSync, writeFileSync, existsSync, statSync, mkdirSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { randomUUID } from 'node:crypto';

const __dirname = dirname(fileURLToPath(import.meta.url));
const WORKSPACE_DIR = join(__dirname, '..', '..');
import os from 'node:os';

const DB_PATH = join(os.homedir(), '.openclaw', 'memory', 'bayra.db');
const SNAPSHOT_PATH = join(WORKSPACE_DIR, 'memory', 'archive', 'MEMORY_SNAPSHOT.md');

// ─── Export Snapshot ───────────────────────────────────────────────

export function exportSnapshot(db) {
  // Get all high-importance memories (semantic + procedural)
  const memories = db.prepare(`
    SELECT id, type, subtype, content, summary, importance, tags, created_at, updated_at
    FROM memories
    WHERE status = 'active'
      AND (type IN ('semantic', 'procedural') OR importance >= 8)
    ORDER BY importance DESC, updated_at DESC
  `).all();

  if (memories.length === 0) return 0;

  const now = new Date().toISOString().replace('T', ' ').substring(0, 19);
  let output = `# 🧠 Bayra Memory Snapshot\n\n`;
  output += `> Auto-generated by Bayra Memory System. Edit with care.\n`;
  output += `> If bayra.db is lost, the system can auto-hydrate from this file.\n\n`;
  output += `**Last exported:** ${now}\n`;
  output += `**Total memories:** ${memories.length}\n\n---\n\n`;

  for (const m of memories) {
    output += `### ${m.type}/${m.subtype || 'general'} ★${m.importance}\n\n`;
    output += `${m.content}\n\n`;
    if (m.tags) output += `Tags: ${m.tags}\n`;
    output += `*Created: ${m.created_at} | Updated: ${m.updated_at}*\n\n---\n\n`;
  }

  writeFileSync(SNAPSHOT_PATH, output, 'utf-8');
  return memories.length;
}

// ─── Check if Should Hydrate ───────────────────────────────────────

export function shouldHydrate() {
  const dbPath = join(os.homedir(), '.openclaw', 'memory', 'bayra.db');
  const dbMissing = !existsSync(dbPath) || statSync(dbPath).size < 4096;
  const snapshotExists = existsSync(SNAPSHOT_PATH);
  return dbMissing && snapshotExists;
}

// ─── Hydrate from Snapshot ─────────────────────────────────────────

export function hydrateFromSnapshot(db) {
  if (!existsSync(SNAPSHOT_PATH)) return 0;

  const content = readFileSync(SNAPSHOT_PATH, 'utf-8');
  const entries = parseSnapshot(content);
  
  if (entries.length === 0) return 0;

  // Use db directly for createMemory-like inserts
  const now = new Date().toISOString().replace(/\.\d{3}Z$/, 'Z');
  let hydrated = 0;

  const stmt = db.prepare(`
    INSERT OR IGNORE INTO memories (id, type, subtype, content, importance, tags, source, channel, status, visibility, created_at, updated_at)
    VALUES (?, ?, ?, ?, ?, ?, 'snapshot-hydration', 'snapshot', 'active', 'private', ?, ?)
  `);
  
  for (const entry of entries) {
    try {
      const result = stmt.run(randomUUID(), entry.type, entry.subtype, entry.content, entry.importance, entry.tags, now, now);
      if (result.changes > 0) hydrated++;
    } catch (err) {
      // Likely duplicate, skip
    }
  }

  return hydrated;
}

// ─── Parse Snapshot ────────────────────────────────────────────────

function parseSnapshot(input) {
  const entries = [];
  const lines = input.split('\n');
  let current = null;
  let contentLines = [];

  for (const line of lines) {
    // Match: ### type/subtype ★importance
    const headerMatch = line.match(/^### (\w+)\/(\w+) ★(\d+)/);
    if (headerMatch) {
      if (current && contentLines.length > 0) {
        current.content = contentLines.join('\n').trim();
        entries.push(current);
      }
      current = {
        type: headerMatch[1],
        subtype: headerMatch[2] === 'general' ? null : headerMatch[2],
        importance: parseInt(headerMatch[3]),
        tags: null,
        content: '',
      };
      contentLines = [];
      continue;
    }

    if (current) {
      if (line.startsWith('Tags: ')) {
        current.tags = line.substring(6).trim();
      } else if (line.startsWith('*Created:') || line === '---') {
        // metadata line, skip
      } else {
        contentLines.push(line);
      }
    }
  }

  // Last entry
  if (current && contentLines.length > 0) {
    current.content = contentLines.join('\n').trim();
    entries.push(current);
  }

  return entries.filter(e => e.content.length > 10);
}

// ─── CLI ───────────────────────────────────────────────────────────

const isMain = process.argv[1]?.endsWith('snapshot.mjs');
if (isMain) {
  const action = process.argv[2] || 'export';
  const { getDb } = await import('./db.mjs');
  const db = getDb();

  if (action === 'export') {
    const count = exportSnapshot(db);
    console.log(`📸 Exported ${count} memories to MEMORY_SNAPSHOT.md`);
  } else if (action === 'hydrate') {
    const count = hydrateFromSnapshot(db);
    console.log(`🧬 Hydrated ${count} memories from snapshot`);
  } else {
    console.log('Usage: node snapshot.mjs [export|hydrate]');
  }
}
