export const DELIVERY_DEDUCTION_PERCENT = { MINOR: 3, MODERATE: 7, MAJOR: 12 } as const;
export const MONTHLY_DEDUCTION_CAP_PERCENT = 25;
export const DELIVERY_MIN_LEAD_TIME_HOURS = 24;
export const QUALITY_AVG_ROUNDS_THRESHOLD = 2;
export const QUALITY_REJECTION_RATE_THRESHOLD_PERCENT = 20;
export const QUALITY_CONSECUTIVE_MONTHS_REQUIRED = 2;

export const ATTENDANCE_DEDUCTION_UNITS = {
  FREE: 0,
  QUARTER: 0.25,
  HALF: 0.5,
  FULL: 1,
} as const;
export const ATTENDANCE_QUARTER_DAY_MAX_MINUTES = 60;
export const ATTENDANCE_HALF_DAY_MAX_MINUTES = 120;
