#!/usr/bin/env tsx
/**
 * scripts/create-test-accounts.ts
 *
 * Creates the two PERMANENT test accounts used for verifying auth/permission
 * work without ever logging in as a real employee.
 *
 * WHY THIS EXISTS:
 *   Logging in as a real sales agent (youssef / cosette) rotates their device
 *   key and kills the call-tracking app on their phone. Security fixes still
 *   have to be proven from a non-admin session. These two accounts are that
 *   session.
 *
 *   - test.sales  → role 'sales_agent', mirrors youssef (same role_id, manager)
 *   - test.admin  → role 'admin',       mirrors elharm  (same role_id)
 *
 * Uses the app's own createEmployeeUser() so the rows are identical to what
 * POST /api/users produces — auth user + pyra_users + pyra_auth_mapping +
 * leave balances — including its rollback chain on partial failure.
 *
 * Credentials are written to .env.test.local, which is covered by the
 * `.env*.local` rule in .gitignore. They are LOCAL ONLY — never commit, never
 * push, never paste into a chat or an issue.
 *
 * Idempotent: createEmployeeUser returns 409 if the username already exists,
 * so re-running reports "already exists" instead of duplicating. To rotate a
 * password, delete the account first or reset it from the admin UI.
 *
 * Run:  npx tsx scripts/create-test-accounts.ts
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs';
import { randomBytes } from 'node:crypto';
import { createClient } from '@supabase/supabase-js';
import { createEmployeeUser } from '@/lib/hr/create-employee';

// ── Env (read from .env.local only — same discipline as scripts/db-query.ts) ──
function readEnvLocal(): Record<string, string> {
  if (!existsSync('.env.local')) throw new Error('.env.local not found — run from the repo root');
  const out: Record<string, string> = {};
  for (const line of readFileSync('.env.local', 'utf8').split('\n')) {
    const m = line.match(/^\s*([A-Z0-9_]+)\s*=\s*(.*)$/);
    if (m) out[m[1]] = m[2].trim().replace(/^["']|["']$/g, '');
  }
  return out;
}

const env = readEnvLocal();
const URL = env.NEXT_PUBLIC_SUPABASE_URL;
const SERVICE = env.SUPABASE_SERVICE_ROLE_KEY;
if (!URL || !SERVICE) throw new Error('Missing NEXT_PUBLIC_SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env.local');

// Role FKs copied from the live rows these accounts mirror.
const ROLE_ID_SALES = '70167f39-40e1-4ede-a4e7-71db2b09b0a3'; // youssef / cosette ('Sales')
const ROLE_ID_ADMIN = '8a990b30-8bf3-4f81-8bea-c5adeb7481de'; // elharm

/** Random password, URL-safe, ~96 bits of entropy. */
function makePassword(): string {
  return 'Ptest-' + randomBytes(12).toString('base64url');
}

const ACCOUNTS = [
  {
    username: 'test.sales',
    role: 'sales_agent',
    role_id: ROLE_ID_SALES,
    display_name: 'TEST — Sales Agent',
    job_title: 'Test Account (Sales)',
    manager_username: 'elharm' as string | null,
    // Distinctive salaries so an exploit read is unmistakable in output.
    salary: 12345,
  },
  {
    username: 'test.admin',
    role: 'admin',
    role_id: ROLE_ID_ADMIN,
    display_name: 'TEST — Admin',
    job_title: 'Test Account (Admin)',
    manager_username: null as string | null,
    salary: 54321,
  },
];

async function main() {
  const svc = createClient(URL, SERVICE, {
    auth: { autoRefreshToken: false, persistSession: false },
  });

  const created: { username: string; password: string; role: string }[] = [];

  for (const acc of ACCOUNTS) {
    const password = makePassword();
    const res = await createEmployeeUser(svc, {
      username: acc.username,
      password,
      role: acc.role,
      role_id: acc.role_id,
      display_name: acc.display_name,
      job_title: acc.job_title,
      manager_username: acc.manager_username,
      employment_type: 'full_time',
      work_location: 'onsite',
      payment_type: 'monthly_salary',
      salary: acc.salary,
      salary_currency: 'AED',
    });

    if (!res.ok) {
      console.error(`SKIPPED ${acc.username}: [${res.status}] ${res.error}`);
      continue;
    }
    console.log(`created  ${res.user.username}  role=${res.user.role}`);
    created.push({ username: acc.username, password, role: acc.role });
  }

  if (!created.length) {
    console.error('\nNo accounts created — .env.test.local left untouched.');
    return;
  }

  const path = '.env.test.local';
  const header = [
    '# ============================================================',
    '# LOCAL TEST ACCOUNTS — NEVER COMMIT, NEVER PUSH',
    '# Covered by the `.env*.local` rule in .gitignore.',
    '# Sign in at https://workspace.pyramedia.cloud with the USERNAME.',
    `# Generated by scripts/create-test-accounts.ts on ${new Date().toISOString()}`,
    '# ============================================================',
    '',
  ].join('\n');

  const body = created
    .map((c) => {
      const k = c.username.replace(/[.\-]/g, '_').toUpperCase();
      return [
        `# ${c.username}  (role: ${c.role})`,
        `${k}_USERNAME=${c.username}`,
        `${k}_EMAIL=${c.username}@pyra.local`,
        `${k}_PASSWORD=${c.password}`,
        '',
      ].join('\n');
    })
    .join('\n');

  const prev = existsSync(path) ? readFileSync(path, 'utf8') : '';
  writeFileSync(path, header + body + (prev ? '\n# ── superseded ──\n' + prev : ''), 'utf8');
  console.log(`\ncredentials written to ${path}  (gitignored)`);
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
